import React from 'react';
import { motion } from 'motion/react';
import { ShieldCheck, FileText, ArrowLeft, Printer, ExternalLink, Scale, CheckCircle2, Building2 } from 'lucide-react';

interface TermsViewProps {
  onBackToHome?: () => void;
}

export function TermsView({ onBackToHome }: TermsViewProps) {
  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="mx-auto max-w-5xl px-4 py-8 sm:px-6 lg:px-8 space-y-8">
      {/* Top Breadcrumb & Action Bar */}
      <div className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-100 pb-4 print:hidden">
        <button
          onClick={onBackToHome}
          className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2 text-xs font-bold text-slate-700 shadow-sm transition-all hover:bg-slate-50 hover:text-sea-green active:scale-95"
        >
          <ArrowLeft size={16} />
          Back to Home
        </button>

        <div className="flex items-center gap-3">
          <button
            onClick={handlePrint}
            className="inline-flex items-center gap-2 rounded-xl bg-slate-100 px-4 py-2 text-xs font-bold text-slate-700 transition-all hover:bg-slate-200 active:scale-95"
          >
            <Printer size={16} />
            Print / Save PDF
          </button>
        </div>
      </div>

      {/* Header Banner */}
      <motion.div
        initial={{ opacity: 0, y: 15 }}
        animate={{ opacity: 1, y: 0 }}
        className="rounded-3xl bg-slate-900 p-8 text-white shadow-xl relative overflow-hidden"
      >
        <div className="absolute -right-16 -top-16 h-64 w-64 rounded-full bg-sea-green/20 blur-3xl pointer-events-none"></div>
        <div className="relative z-10 space-y-4">
          <div className="inline-flex items-center gap-2 rounded-full bg-sea-green/20 px-3.5 py-1.5 text-xs font-bold text-sea-green-light border border-sea-green/30">
            <Scale size={14} />
            Official Platform Document
          </div>
          <h1 className="text-3xl font-black tracking-tight sm:text-5xl">
            Terms & Conditions
          </h1>
          <p className="max-w-2xl text-sm sm:text-base text-slate-300 leading-relaxed font-normal">
            Please read these Terms of Use carefully before accessing or using our website, platform, and services.
          </p>

          <div className="pt-4 flex flex-wrap gap-6 text-xs text-slate-400 border-t border-slate-800">
            <div className="flex items-center gap-2">
              <Building2 size={14} className="text-sea-green" />
              <span>Platform: <strong className="text-slate-200">A D Professional Solution</strong></span>
            </div>
            <div className="flex items-center gap-2">
              <ExternalLink size={14} className="text-sea-green" />
              <span>Website: <a href="https://www.adprosol.in/" target="_blank" rel="noopener noreferrer" className="text-sea-green-light hover:underline font-mono">https://www.adprosol.in/</a></span>
            </div>
            <div className="flex items-center gap-2">
              <ShieldCheck size={14} className="text-sea-green" />
              <span>Jurisdiction: <strong className="text-slate-200">West Bengal, India</strong></span>
            </div>
          </div>
        </div>
      </motion.div>

      {/* Document Main Content Card */}
      <motion.div
        initial={{ opacity: 0, y: 15 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.1 }}
        className="rounded-3xl border border-slate-200 bg-white p-6 sm:p-10 shadow-sm space-y-8 text-slate-800 text-sm sm:text-base leading-relaxed"
      >
        {/* Intro clauses 1 to 6 */}
        <div className="space-y-6">
          <div className="rounded-2xl bg-amber-50/80 border border-amber-200/80 p-5 text-amber-900 text-xs sm:text-sm font-medium leading-relaxed">
            <p className="font-extrabold uppercase tracking-wider mb-1 flex items-center gap-2 text-amber-950">
              <FileText size={16} /> Important Notice
            </p>
            This document is an electronic record generated by a computer system and does not require any physical or digital signatures. ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE.
          </div>

          <div className="space-y-4 text-slate-700">
            <div className="flex gap-4 p-4 rounded-2xl bg-slate-50 border border-slate-100">
              <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-sea-green-light text-sea-green font-bold text-xs">1</span>
              <div>
                <p>
                  This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                </p>
              </div>
            </div>

            <div className="flex gap-4 p-4 rounded-2xl bg-slate-50 border border-slate-100">
              <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-sea-green-light text-sea-green font-bold text-xs">2</span>
              <div>
                <p>
                  This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name{' '}
                  <a href="https://www.adprosol.in/" target="_blank" rel="noopener noreferrer" className="font-bold text-sea-green hover:underline">
                    https://www.adprosol.in/
                  </a>{' '}
                  ('Website'), including the related mobile site and mobile application (hereinafter referred to as 'Platform').
                </p>
              </div>
            </div>

            <div className="flex gap-4 p-4 rounded-2xl bg-slate-50 border border-slate-100">
              <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-sea-green-light text-sea-green font-bold text-xs">3</span>
              <div>
                <p>
                  The Platform is owned by <strong>8777561824</strong>, a company incorporated under the Companies Act, 1956 with its registered office at <strong>North 24 Parganas, West Bengal, India, 743145</strong> (hereinafter referred to as ‘Platform Owner’, 'we', 'us', 'our').
                </p>
              </div>
            </div>

            <div className="flex gap-4 p-4 rounded-2xl bg-slate-50 border border-slate-100">
              <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-sea-green-light text-sea-green font-bold text-xs">4</span>
              <div>
                <p>
                  Your use of the Platform and services and tools are governed by the following terms and conditions (“Terms of Use”) as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations, with Platform Owner. These Terms of Use relate to your use of our website, goods (as applicable) or services (as applicable) (collectively, 'Services'). Any terms and conditions proposed by You which are in addition to or which conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect. These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates.
                </p>
              </div>
            </div>

            <div className="flex gap-4 p-4 rounded-2xl bg-slate-50 border border-slate-100">
              <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-sea-green-light text-sea-green font-bold text-xs">5</span>
              <div>
                <p>
                  For the purpose of these Terms of Use, wherever the context so requires ‘you’, 'your' or ‘user’ shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.
                </p>
              </div>
            </div>

            <div className="flex gap-4 p-4 rounded-2xl bg-slate-900 text-white border border-slate-800">
              <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-sea-green text-white font-bold text-xs">6</span>
              <div>
                <p className="font-bold tracking-tight text-sea-green-light uppercase text-xs sm:text-sm">
                  ACCESSING, BROWSING OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING.
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Section 7: General Terms of Use Sub-items */}
        <div className="space-y-4 pt-4 border-t border-slate-100">
          <div className="flex items-center gap-3">
            <span className="flex h-8 w-8 items-center justify-center rounded-xl bg-sea-green text-white font-black text-sm">7</span>
            <h2 className="text-lg sm:text-xl font-extrabold text-slate-900">
              Terms of Use for Platform and Services
            </h2>
          </div>
          <p className="text-xs text-slate-500 italic pl-11">
            The use of Platform and/or availing of our Services is subject to the following Terms of Use:
          </p>

          <div className="grid gap-3.5 pl-2 sm:pl-6">
            {[
              {
                num: "7.1",
                text: "To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform."
              },
              {
                num: "7.2",
                text: "Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services, for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law."
              },
              {
                num: "7.3",
                text: "Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements."
              },
              {
                num: "7.4",
                text: "The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The contents includes and is not limited to the design, layout, look and graphics."
              },
              {
                num: "7.5",
                text: "You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws."
              },
              {
                num: "7.6",
                text: "You agree to pay us the charges associated with availing the Services."
              },
              {
                num: "7.7",
                text: "You agree not to use the Platform and/ or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you."
              },
              {
                num: "7.8",
                text: "You agree and acknowledge that website and the Services may contain links to other third party websites. On accessing these links, you will be governed by the terms of use, privacy policy and such other policies of such third party websites. These links are provided for your convenience for provide further information."
              },
              {
                num: "7.9",
                text: "You understand that upon initiating a transaction for availing the Services you are entering into a legally binding and enforceable contract with the Platform Owner for the Services."
              }
            ].map((sub, idx) => (
              <div key={idx} className="flex gap-3.5 p-3.5 rounded-xl border border-slate-100 bg-slate-50/50 hover:bg-slate-50 transition-colors">
                <CheckCircle2 size={18} className="mt-0.5 shrink-0 text-sea-green" />
                <div>
                  <span className="font-extrabold text-xs text-slate-700 mr-2">[{sub.num}]</span>
                  <span className="text-slate-700 leading-relaxed text-xs sm:text-sm">{sub.text}</span>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Clauses 8 to 12 (or 10 to 14) */}
        <div className="space-y-4 pt-4 border-t border-slate-100">
          <div className="space-y-4 text-slate-700">
            <div className="flex gap-4 p-4 rounded-2xl bg-slate-50 border border-slate-100">
              <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-sea-green-light text-sea-green font-bold text-xs">8</span>
              <div>
                <h3 className="font-bold text-slate-900 mb-1 text-xs sm:text-sm uppercase tracking-wide">Indemnification</h3>
                <p>
                  You shall indemnify and hold harmless Platform Owner, its affiliates, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorney's fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.
                </p>
              </div>
            </div>

            <div className="flex gap-4 p-4 rounded-2xl bg-slate-50 border border-slate-100">
              <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-sea-green-light text-sea-green font-bold text-xs">9</span>
              <div>
                <h3 className="font-bold text-slate-900 mb-1 text-xs sm:text-sm uppercase tracking-wide">Force Majeure</h3>
                <p>
                  Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.
                </p>
              </div>
            </div>

            <div className="flex gap-4 p-4 rounded-2xl bg-slate-50 border border-slate-100">
              <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-sea-green-light text-sea-green font-bold text-xs">10</span>
              <div>
                <h3 className="font-bold text-slate-900 mb-1 text-xs sm:text-sm uppercase tracking-wide">Governing Law</h3>
                <p>
                  These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India.
                </p>
              </div>
            </div>

            <div className="flex gap-4 p-4 rounded-2xl bg-slate-50 border border-slate-100">
              <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-sea-green-light text-sea-green font-bold text-xs">11</span>
              <div>
                <h3 className="font-bold text-slate-900 mb-1 text-xs sm:text-sm uppercase tracking-wide">Jurisdiction</h3>
                <p>
                  All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in West Bengal, India.
                </p>
              </div>
            </div>

            <div className="flex gap-4 p-4 rounded-2xl bg-sea-green-light/40 border border-sea-green/20">
              <span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-lg bg-sea-green text-white font-bold text-xs">12</span>
              <div>
                <h3 className="font-bold text-sea-green-dark mb-1 text-xs sm:text-sm uppercase tracking-wide">Concerns & Communications</h3>
                <p className="text-slate-800">
                  All concerns or communications relating to these Terms must be communicated to us using the contact information provided on this website (<strong className="text-sea-green">adprofessionalsolution@gmail.com</strong>).
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Footer info inside Card */}
        <div className="pt-6 border-t border-slate-100 flex flex-col sm:flex-row items-center justify-between text-xs text-slate-400 gap-4">
          <div>
            Registered Office: North 24 Parganas, West Bengal, India, 743145
          </div>
          <div>
            © A D Professional Solution. All Rights Reserved.
          </div>
        </div>
      </motion.div>
    </div>
  );
}
